### ISSUE TITLE
API calls with sensitive data should be made through HTTPS

### ISSUE THREAD

**Issue by 0xCAFEADD1C7** [Roba1993/SPE3D#19]
I am no Rust expert so I won't PR it, but I can see that the Share Online loader uses the Share Online API through HTTP. I think it should call it through HTTPS, since data such as password is sent.

**Comment by Roba1993** [comment]
You're totally right!
I fixed it locally - with the next stack of changes, this will be closed.

If you have any other suggestion for change, please let me know 👍
